# Sirve la web del verificador + issuer.json + certs sobre HTTP (8089) y HTTPS (8443).
# El componente blockcerts-verifier fuerza HTTPS al traer el issuer profile,
# por eso el HTTPS es obligatorio para la verificación.

server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    location / { try_files $uri $uri/ =404; }
    add_header Access-Control-Allow-Origin *;
}

server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate     /etc/nginx/tls/localhost.crt;
    ssl_certificate_key /etc/nginx/tls/localhost.key;

    root /usr/share/nginx/html;
    location / { try_files $uri $uri/ =404; }
    add_header Access-Control-Allow-Origin *;
}
